
ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "docker.sh"

  NodeCount = 1

  (1..NodeCount).each do |i|
    config.vm.define "dockerUbuntu" do |node|
      node.vm.box = "bento/ubuntu-20.04"
      node.vm.hostname = "dockerUbuntu.example.com"
      node.vm.network "private_network", ip: "172.168.16.10#{i}"
      node.vm.provider "virtualbox" do |v|
        v.name = "dockerUbuntu"
        v.memory = 2048
        v.cpus = 1
      end
    end
  end

end
